---
# add name of the host: web
# see the logs whilst executing
# provide admin access
- hosts: web
  gather_facts: yes
  become: true

# run provison.sh bash script
  tasks:
  - name: Run provision.sh bash script
    command: bash ./environment/app/provision.sh

# make env variable 
  - name: set DB_host
    lineinfile:
      path: /etc/environment
      line: 'DB_HOST=mongodb://18.201.198.74:27017/posts'
      create: yes

# navigate to /home/ubuntu/app/ folder
  - name: Navigate to /app/ folder
    shell: |
      cd /home/ubuntu/app
      export DB_HOST=mongodb://172.31.41.153:27017/posts
      sudo -E npm install
      sudo -E npm install pm2 -g
      cd /home/ubuntu/app/seeds
      node seed.js &
      cd /home/ubuntu/app
      sudo pm2 kill
      sudo -E pm2 start app.js
